apiVersion: v1
kind: Service #  Deployment or Service
metadata:
  name: udacity-api-user
  labels:
    run: udacity-api-user
spec:
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 32702
    protocol: TCP
  selector:
    run: udacity-api-user