apiVersion: v1
kind: Service #  Deployment or Service
metadata:
  name: udacity-api-user
  labels:
    run: udacity-api-user
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: udacity-api-user